### ISSUE TITLE
Broke with Raised

### ISSUE THREAD

**Issue by Arborsm** [tr7zw/Exordium#126]
[25Dec2023 17:10:48.541] [Worker-ResourceReload-3/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLClientSetupEvent dispatch for modid raised
java.lang.IllegalStateException: Rendersystem called from wrong thread
at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:184) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThreadOrInit(RenderSystem.java:168) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
at com.mojang.blaze3d.pipeline.TextureTarget.(TextureTarget.java:8) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
at dev.tr7zw.exordium.util.BufferedComponent.(BufferedComponent.java:23) ~[exordium-forge-1.2.1-mc1.20.1.jar%23390!/:1.2.1-mc1.20.1]
at net.minecraft.client.gui.Gui$Anonymous$3fe96e9b01954e678ae7edc00f8cfe6e.(CrosshairMixin.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
at net.minecraft.client.gui.Gui.(Gui.java:127) ~[client-1.20.1-20230612.114412-srg.jar%23496!/:?]
at net.minecraftforge.client.gui.overlay.ForgeGui.(ForgeGui.java:69) ~[forge-1.20.1-47.2.18-universal.jar%23501!/:?]
at dev.yurisuika.raised.client.gui.RaisedGui.(RaisedGui.java:37) ~[raised-forge-1.20.1-3.1.0.jar%23456!/:?]
at dev.yurisuika.raised.Raised$ClientModBusEvents.clientSetup(Raised.java:45) ~[raised-forge-1.20.1-3.1.0.jar%23456!/:?]
at dev.yurisuika.raised.__ClientModBusEvents_clientSetup_FMLClientSetupEvent.invoke(.dynamic) ~[raised-forge-1.20.1-3.1.0.jar%23456!/:?]
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?]
at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.18.jar%23498!/:?]
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.18.jar%23497!/:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]

**Comment by tr7zw** [comment]
The Forge version of this mod has been removed from the sites and I don't intend to try to release a working version of it(it doesn't even work on its own).
